[package]
name = "pbf_history_reader"
version = "1.3.2"
edition = "2021"
rust-version = "1.93.1"

[dependencies]
osmpbf = "0.3.0"
strum = "0.24"
strum_macros = "0.24"
chrono = "0.4.24"
postgres = {version = "0.19.5", features = ["array-impls", "with-chrono-0_4"]}
native-tls = "0.2"
postgres-native-tls = "0.5"
itertools = "0.10.5"