name: Rust compile & release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      # https://github.com/actions-rs/toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose

    - name: Create Release
      # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v1
      with:
        files: target/x86_64-unknown-linux-musl/release/*
        tag_name: v1.0.0
        release_name: Release v1.1.0
